name: "wav2vec"
architecture: "wav2vec2"
pretrained: "facebook/wav2vec2-base"
ignore_unused_weights: true
matmul_precision: "medium"

# 모델 freezing 설정
freeze:
  enabled: true
  num_unfrozen_layers: 2
  layer_dropout: 0.1

# 분류기 설정
classifier:
  hidden_size: 512
  dropout: 0.4
