name: emotion-recognition
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.1.1
  - torchvision=0.16.1
  - torchaudio=2.1.1
  - transformers=4.46.1
  - pytorch-lightning=2.1.0
  - omegaconf=2.3.0
  - kaggle=1.5.12
  - dotenv=0.22.1
  - hydra-core=1.4.0
  - wandb=0.15.1
  - pandas=1.5.3
  - numpy=1.23.5
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - tqdm=4.66.4
  - dotenv=0.22.1
  - wandb=0.15.1
  - albumentations=1.3.0
  # soundfile과 audioread는 torchaudio의 백엔드로 사용됩니다
  - soundfile
  - audioread
  - librosa
  - matplotlib
  - seaborn
  - accelerate

# libsndfile는 시스템 레벨 의존성입니다
# Ubuntu/Debian
# sudo apt-get install libsndfile1

# # librosa도 설치 (추가 기능을 위해)
# pip install librosa