train:
  metrics:
    - accuracy
    - macro_f1

val:
  metrics:
    - accuracy
    - macro_f1

test:
  metrics:
    - accuracy
    - macro_f1
  
  main_metric: macro_f1
  monitor_metrics:
    - macro_f1
    - accuracy 