metrics:
  train:
    metrics: ["loss", "accuracy", "f1", "precision", "recall"]
  val:
    metrics: ["loss", "accuracy", "f1", "precision", "recall"]
    monitor: "loss"
  test:
    metrics: ["loss", "accuracy", "f1", "precision", "recall"]
    monitor_metrics: ["f1", "accuracy", "loss"]
    main_metric: "f1" 