max_epochs: 3
batch_size: 8
num_workers: 2
learning_rate: 1e-4
weight_decay: 1e-4
gradient_clip_val: 1.0
accumulate_grad_batches: 2

scheduler:
  enabled: true
  type: "cosine"
  warmup_epochs: 5

# 메모리 관리 설정 추가
memory_management:
  pin_memory: false
  persistent_workers: false
  prefetch_factor: 2

# 데이터로더 설정
dataloader:
  shuffle: true
  drop_last: false
