name: "image_emotion"
architecture: "resnet"  # or "efficientnet"
hidden_size: 512
dropout: 0.3
pretrained: true

training:
  weight_decay: 1e-4
  learning_rate: 1e-4
  scheduler:
    enabled: true
    type: "cosine"
    warmup_epochs: 5 