name: "fer2013"
root_dir: "data/fer2013"

image:
  size: [48, 48]
  channels: 1
  normalize: true
  mean: [0.5]
  std: [0.5]

augmentation:
  enabled: true
  rotation_range: 10
  horizontal_flip: true
  random_crop:
    enabled: true
    scale: [0.8, 1.0]

splits:
  train: "train"
  val: "val"
  test: "test"
  ratios:
    train: 0.8
    val: 0.1
    test: 0.1

num_classes: 7
class_names: [
  "angry",
  "disgust",
  "fear",
  "happy",
  "sad",
  "surprise",
  "neutral"
]

split_method: "random"
seed: 42