name: "fer2013"
root_dir: "data/fer2013"

image:
  size: [48, 48]
  channels: 1
  normalize: true
  mean: [0.5]
  std: [0.5]

augmentation:
  enabled: true
  neutral_aug_factor: 2
  rotation_range: 10
  horizontal_flip: true
  random_crop:
    enabled: true
    scale: [0.8, 1.0]
  noise:
    enabled: true
    std: 0.1

splits:
  method: "stratified"
  train: "train"
  val: "val"
  test: "test"
  ratios:
    train: 0.8
    val: 0.1
    test: 0.1

num_classes: 7
class_names: [
  "angry",
  "disgust",
  "fear",
  "happy",
  "sad",
  "surprise",
  "neutral"
]

split_method: "random"
seed: 42

class_weights:
  mode: "manual"  # "auto", "manual", "none"
  manual_weights:
    "angry": 0.5
    "disgust": 1.3
    "fear": 1.0
    "happy": 0.8
    "sad": 1.2
    "surprise": 1.0
    "neutral": 3.0

weighted_sampling:
  enabled: true

# 클래스 밸런싱 설정
balance:
  enabled: true
  method: "oversample"  # "oversample" or "undersample"
  target_size: "auto"  # "auto" or specific number