name: "ravdess"
root_dir: "data/ravdess"

# 기본 설정
seed: 42  # 랜덤 시드 추가

# 오디오 설정
audio:
  sample_rate: 16000
  duration: 3.0
  max_length: 48000  # duration * sample_rate
  normalize: true

# Augmentation 설정
augmentation:
  enabled: true
  balance_ratio: 1.0  # 최대 클래스 대비 목표 비율
  max_augmentations: 3  # 샘플당 최대 augmentation 횟수
  noise:
    enabled: true
    noise_level: 0.008
  volume:
    enabled: true
    min_gain: 0.75
    max_gain: 1.25
  pitch_shift:
    enabled: false
    min_semitones: -1
    max_semitones: 1
  time_mask:
    enabled: false
    max_mask_size: 100

# 클래스 설정
num_classes: 8
class_names: [
  "neutral",
  "calm",
  "happy",
  "sad",
  "angry",
  "fearful",
  "disgust",
  "surprised"
]

# 클래스 밸런싱 설정
balance:
  enabled: true
  method: "oversample"
  target_size: "auto"

# 클래스 가중치 설정
class_weights:
  mode: "manual"
  manual_weights:
    "neutral": 2.0
    "calm": 1.0
    "happy": 1.5
    "sad": 1.5
    "angry": 1.0
    "fearful": 1.0
    "disgust": 1.0
    "surprised": 1.0

# Split 설정
splits:
  method: "stratified"
  train: "train"
  val: "validation"
  test: "test"
  ratios:
    train: 0.7
    val: 0.15
    test: 0.15

# 디버그 설정 추가
debug:
  enabled: false
  log_shapes: false
  log_values: false