name: "ravdess"
root_dir: "data/ravdess"
 
audio:
  sample_rate: 16000  # wav2vec2 기본 샘플링 레이트
  num_channels: 1     # 모노 오디오
  duration: 5.0      # 오디오 길이
  normalize: true    # 오디오 정규화
  max_length: 10    # 최대 길이 (초)

text:
  max_length: 128

augmentation:
  enabled: true
  balance_ratio: 1.0  # 최대 클래스 대비 목표 비율
  max_augmentations: 3  # 샘플당 최대 augmentation 횟수
  noise:
    enabled: true
    noise_level: 0.008
  volume:
    enabled: true
    min_gain: 0.75
    max_gain: 1.25
  pitch_shift:
    enabled: true
    min_semitones: -1
    max_semitones: 1
  time_mask:
    enabled: true
    max_mask_size: 100

num_classes: 8
class_names: [
  "neutral",
  "calm",
  "happy",
  "sad",
  "angry",
  "fearful",
  "disgust",
  "surprised"
]

# splits 섹션 안으로 이동
splits:
  method: "stratified"  # random, kfold, stratified 중 선택
  k_folds: 5
  current_fold: 0
  stratify: true
  train: "train"
  val: "validation"
  test: "test"
  ratios:
    train: 0.75
    val: 0.15
    test: 0.10

seed: 42  # random seed

# 필터링 설정
filtering:
  enabled: true
  speech_only: true  # 음성만 포함
  emotions: null     # 모든 감정 포함
  exclude_emotions: null
  emotion_intensity: null #[1, 2]  # normal, strong
  statement: null #[1, 2]  # 두 문장 모두 포함
  gender: null       # 모든 성별 포함

# 통계 설정
statistics:
  enabled: true
  save_path: "statistics"
  plot_distributions: true