name: "fer2013"
root_dir: "data/fer2013"

image:
  size: 48  # 원본 이미지 크기
  channels: 1  # grayscale
  normalize: true
  mean: [0.485]  # grayscale mean
  std: [0.229]   # grayscale std

augmentation:
  enabled: true
  rotation_range: 20
  horizontal_flip: true
  random_crop:
    enabled: true
    scale: [0.8, 1.0]

num_classes: 6
class_names: [
  "angry",
  "fear",
  "happy",
  "sad",
  "surprise",
  "neutral"
]

splits:
  train: "train"
  test: "test"
  ratios:  # train 데이터에서 validation split 비율
    train: 0.8
    val: 0.2

split_method: "random"
seed: 42